language: python
python: 2.7
env:
  - ENV=flake8
  - ENV=py27
  - ENV=py34
  - ENV=frontend
  - ENV=jscs
install:
  - pip install coveralls
script:
  - ./travis_run.sh $ENV
after_success:
  - coveralls
notifications:
  email:
    - admin@polybit.org
branches:
  only:
    - master
matrix:
  allow_failures:
    - jscs
  fast_finish: true
