language: python
python: 2.7
env:
  - ENV=flake8
  - ENV=py27
  - ENV=py34
  - ENV=frontend
install:
  - pip install coveralls
script:
  - ./travis_run.sh $ENV
after_success:
  - coveralls
notifications:
  email:
    - admin@polybit.org
